### ISSUE TITLE
Q: How to bind positional arguments in HatchDict?

### ISSUE THREAD

**Issue by npow** [Minyus/pipelinex#17]
I'm trying to use `functools.partial` in HatchDict, but it seems to always require one argument which is not named. Is there any way to work around this?

```
(Pdb) config.get("metrics")
*** TypeError: type 'partial' takes at least one argument
```

config:
```
metrics:
  - =: functools.partial
    func:
      =: sklearn.metrics.roc_auc_score
    multiclass: ovr
```
